# Generated by Django 3.1.2 on 2020-10-17 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tri_Spread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tri_exchange_buy1_id', models.IntegerField()),
                ('tri_exchange_sell_id', models.IntegerField()),
                ('tri_exchange_buy2_id', models.IntegerField()),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('tri_spread', models.IntegerField(blank=True)),
                ('tri_xchange_buy1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tri_exchange_buy1', to='bitcoin_arbitrage.exchange')),
                ('tri_xchange_buy2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tri_exchange_buy2', to='bitcoin_arbitrage.exchange')),
                ('tri_xchange_sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tri_exchange_sell', to='bitcoin_arbitrage.exchange')),
            ],
            options={
                'db_table': 'tri_spread',
                'ordering': ['-recorded_date'],
            },
        ),
    ]
